global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gosol'
    static_configs:
      - targets: ['host.docker.internal:2112']  # Default metrics port for Go apps

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 