apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "0 1 * * *"  # Run at 1 AM every day
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:15-alpine
            command:
            - /bin/sh
            - -c
            - |
              pg_dump -Fc -v \
                -h $(DB_HOST) \
                -U $(DB_USER) \
                -d $(DB_NAME) \
                -f /backup/$(date +%Y%m%d_%H%M%S).dump && \
              gsutil cp /backup/*.dump gs://$(BUCKET_NAME)/$(date +%Y/%m/%d)/
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: user
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: database
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: backup-config
                  key: bucket
            volumeMounts:
            - name: backup
              mountPath: /backup
            - name: gcloud-config
              mountPath: /root/.config/gcloud
              readOnly: true
          volumes:
          - name: backup
            emptyDir: {}
          - name: gcloud-config
            secret:
              secretName: gcloud-key
          restartPolicy: OnFailure

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
data:
  bucket: gosol-db-backups
  retention_days: "30"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  host: postgres-service
  user: postgres
  database: gosol
  maintenance_window: "0 0 * * 0"  # Weekly maintenance at midnight on Sunday 