apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-maintenance
spec:
  schedule: "0 0 * * 0"  # Run at midnight every Sunday
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: maintenance
            image: postgres:15-alpine
            command:
            - /bin/sh
            - -c
            - |
              psql -h $(DB_HOST) -U $(DB_USER) -d $(DB_NAME) << 'EOF'
              -- Create next month's partitions
              SELECT create_next_month_partition();
              
              -- Archive old data
              SELECT archive_old_data(interval '3 months');
              
              -- Vacuum analyze tables
              VACUUM ANALYZE markets;
              VACUUM ANALYZE trades;
              VACUUM ANALYZE orders;
              VACUUM ANALYZE positions;
              VACUUM ANALYZE risk_checks;
              
              -- Update statistics
              ANALYZE VERBOSE;
              EOF
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: user
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: database
          restartPolicy: OnFailure 