global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:2112']
    metrics_path: /metrics

  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:2112']
    metrics_path: /metrics

  - job_name: 'app'
    static_configs:
      - targets: ['app:2112']
    metrics_path: /metrics
